# Generated by Django 4.1.13 on 2023-11-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake_Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.IntegerField()),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
