# Generated by Django 4.1.13 on 2023-11-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake_products',
            name='product_des',
            field=models.TextField(default='Default Description', max_length=500),
        ),
    ]
