# Generated by Django 4.1.13 on 2023-12-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customer_order_cake_products_featured_cake_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
