# Generated by Django 4.1.13 on 2024-01-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_orderitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cancelled'), (1, 'Yet to Deliver'), (2, 'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
